### ISSUE TITLE
The files in this setup_embedding.sh cannot be downloaded

### ISSUE THREAD

**Issue by liyaoshigehaoren** [HKUST-KnowComp/Pronoun-Coref#2]

**Comment by panda0881** [comment]
This is abnormal. You can also download the glove from their official website.

I am not sure if it is blocked somehow. Maybe you can try using a VPN?

Best Regards,
Hongming

**Comment by liyaoshigehaoren** [comment]
Thank you for your reply



---Original---

**Comment by liyaoshigehaoren** [comment]
I am sorry to trobule you.I do not konw your readme "rain your model with: python Train.py YourSettingName",the mean of YourSettingName,can you explain to me please?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hongming ZHANG"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月31日(星期天) 上午8:55
收件人:&nbsp;"HKUST-KnowComp/Pronoun-Coref"<Pronoun-Coref@noreply.github.com&gt;;
抄送:&nbsp;"青寻子"<528775950@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HKUST-KnowComp/Pronoun-Coref] The files in this setup_embedding.sh cannot be downloaded (#2)





 
This is abnormal. You can also download the glove from their official website.
 
I am not sure if it is blocked somehow. Maybe you can try using a VPN?
 
Best Regards,
 Hongming
